### ISSUE TITLE
Fix and Finish private group

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#100]
# Description

Finish hooks and UI for Private group.

In this time, we can add members etc (no check for permissions and in the UI), we can't join request etc

# TODO

- [ ] 1. UI permissions and also in hooks if you can do it as an admin or have the correct permissions
- [ ] 2. We need to not see the messages if you are not a members (almost done, do it also in the hooks)
- [ ] 3. FInish join request and view of join request for admin (not done)
- [ ]

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Frontend Engineer with over 5 years experience.

### How I plan on tackling this issue
Will love to complete this task.
