### ISSUE TITLE
Fix pixel quests OZ and import

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#103]
# Description

We are gonna reused the contract of Art-peace:

Quests and Pixel contract.

# Todo

- [ ] Fix pixel OZ version
- [ ] Fix import of pixel quets
- [ ] Import in lib.cairo with a good import mod/crates management.
- [ ] If others examples need pixel contracts

**Comment by ShantelPeters** [comment]
Please can I work on this?

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi.

**Comment by MSghais** [comment]
We can close this issue @manlikeHB, fix in #104
