### ISSUE TITLE
AVNU Swap hooks

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#167]
# Description

We need to have Ha screen to swap tokens with the AVNU SDK in the React Native app in Typescript.
Minimalistic SWAP UI with tokens available on AVNU, way to add amount and max amount (getting balance of user connected).

# Todo

- [ ] Create swap UI components
- [ ] Inputs: Name, Icon, Price
- [ ] Integrate hooks and functions for AVNU swap in the mobile: 
- [ ] Option: Calldata can be added directly in the api of the apps/data-backend or apps/website NextJS backed

**Comment by petersdt** [comment]
@MSghais  can i work on this task

**Comment by NueloSE** [comment]
@MSghais can i be assigned this task

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi, I'm Qudus Adeyemi, a front-end developer with 2 years of experience in React, TypeScript, and JavaScript, specializing in building pixel-perfect, interactive user interfaces. During the previous OD Hackathon, I contributed by enhancing the Starknet React documentation and implementing the useWatchAssets hook to improve wallet tracking. I also have strong experience with React Query and have successfully applied it in various projects to handle complex use cases.

I’m genuinely excited about this opportunity to deepen my knowledge of Web3 technologies and to contribute to your project. I believe my experience, enthusiasm for learning, and problem-solving skills would make me a strong fit for this task.

I estimate the task will take around 2-4 days to complete and I would love the chance to collaborate with the team. Thank you for considering my application!

### How I plan on tackling this issue
1. Clone the project to my local machine.
2. Set up the project by following the provided documentation.
3. Review the existing codebase.
4. Plan the swap UI development and integration of hooks and functions for AVNU swap in the mobile.
5. Implement the plan.
6. Thoroughly test the hook to ensure it functions as expected.
7. Document the hook for future reference and ease of use.

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I’m a front-end developer with +3 years of experience, and I would love 
to make my first contribution to this project. I'm excited to take
on this issue to challenge myself, and contribute to the project's success.
I'm also a member of the Dojo Coding community from Costa Rica.


### How I plan on tackling this issue
I’ll first review the existing project architecture and infrastructure requirements to ensure I have a complete understanding of what is needed for AFK-AlignedFamKernel 

I will create a swap UI where users can choose tokens, input the amount they want to swap, and see their balance, with the option to use the "max amount" based on their balance. I'll connect this UI to the AVNU SDK, which will handle the actual token swap based on the user's input.

To make it easier for users, I'll also set up a way to fetch and display their balance, ensuring they can swap the maximum amount if desired.

ETA: 3-4days


If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years experience

### How I plan on tackling this issue
-Create hook to consume avnu adk.
-Create a swap component and integrate the hook created.
-Test and make sure everything works properly.

ETA: 48hrs
