### ISSUE TITLE
Cashu NIP 60 and 61 with enhancement, test and verify integration

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#168]
# Finish Cashu BTC integration

NIP 60 and 61:

https://github.com/nostr-protocol/nips/blob/master/60.md
https://github.com/nostr-protocol/nips/blob/master/61.md

Docs:
https://github.com/cashubtc/cashu-ts

Wallet example:
https://github.com/cashubtc/cashu.me

https://wallet.cashu.me/#/

https://docs.cashu.space/wallets

# TODO

- [ ]  NIP 60
- [ ] NIP 61: Balance, proofs, spents directly with Nostr about my Cashu wallet

# To verify
- [ ] Unit (sats etc ofr the mint), and conversion
- [ ] Table for Invoices 
- [ ] Table for tx out and in
- [ ] Contact better UI: ADD contact, Send to contact
- [ ] Scan and QR code ui
- [ ] Received modal
- [ ] Send modal
- [ ] ReceivedCashuScreen with cashu parameters
- [ ] Test the Cashu BTC wallet directly to receive/send and ecash/sats.
- [ ] Contact management
- [ ] Enhance the UI 
- [ ] Test every proofs, invoices etc are correctly saved in Localstorage
- [ ] Mint relays to select
- [ ] QR Code generation
- [ ] Pay LN invoice
- [ ] Send P2P 
- [ ] Receive

- [ ] LN address in profile

## Screens to upgrade

Invoices 

![image](https://github.com/user-attachments/assets/fbb3fe2d-2909-45cb-b664-b02140a2e829)

History

![image](https://github.com/user-attachments/assets/d12531d0-9867-4d95-9de2-46a219371013)

Send modal ecash or invoice:

![image](https://github.com/user-attachments/assets/c4c3a1b0-0474-4602-8286-b8c5a3322d7c)

Contact management:

![image](https://github.com/user-attachments/assets/70313eb5-69ad-4175-8f6d-2ab9c425edea)

![image](https://github.com/user-attachments/assets/2c67e8d9-e30a-4686-a30b-ce688cad3543)

Receive invoice or ecash: 

![image](https://github.com/user-attachments/assets/14f85809-3382-4d10-af62-e8502c9cbb8e)

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will finish the Cashu BTC integration by completing hooks in packages/afk_nostr_sdk and mobile UI components. I'll test wallet functionality (send/receive e-cash/sats) and ensure proofs/invoices are saved in local storage. I will enhance the UI, test QR code generation, LN invoice payments, and P2P transfers. I'll also implement NIP 60/61 for relay selection and LN addresses in profiles, following the provided docs and wallet example.

**Comment by petersdt** [comment]
@MSghais can i work on this

**Comment by NueloSE** [comment]
@MSghais can i work on this

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello @MSghais I'm a front-end and a blockchain developer. I will love to work on this please

**Comment by akintewe** [comment]
hello @MSghais  can i be assigned this issue

**Comment by ctangarife** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Backend Developer | Automation Enthusiast

I'm a backend developer driven by a passion for continuous learning. I focus on acquiring new skills either based on project needs or out of personal curiosity. My approach is centered on providing practical solutions to processes that take up too much time. If something can be automated, I rarely do it more than twice. I enjoy creating bash scripts to speed up my workflow.

I have experience in Go, JavaScript, Python, Docker, MongoDB, and I use Git for version control to ensure seamless development.

"Laziness is the mother of automation."

https://www.linkedin.com/in/ctangarife/

### How I plan on tackling this issue
The first thing I do is analyze the potential impact. Then, I review the functions involved leading up to the issue. After that, I focus on the specific function, checking the logic that might be causing the problem.

**Comment by JosephKeswet** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a frontend developer with 3years of experience. I've worked on multiple payment systems. Worked on mobile app using NFC for payment. I'm hardworking and get things done fast and in the most optimized way while also following best practices.

### How I plan on tackling this issue
I'll first look at the structure of how API integration and make sure it is following best practices and there is abstraction of business logic from my UI. Following software architecture principles. Then I'd go onto make sure error handling is taken care of in a neat way. Then start fixing layout issues and making the app look clean and the flow seamless. Finally go into state management to avoid querying endpoints at multiple instances to prevent multiple calls of data that doesn't frequenlty change. Hence reducing the number of network requests.

**Comment by Gianfranco99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have been working as a full stack programmer for 4 years, and it has been 1 year since I started contributing to starknet, my last contributions were for cairo lint and scaffold-starknet

### How I plan on tackling this issue
It is not difficult to carry out this and it is a good factor to get to know the project, since it covers a little of everything. I am looking for an issue like this to gain confidence in the project and increasingly be able to take on more complex issues.

**Comment by jedstroke** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am Jedidiah Gabriel, a seasoned fullstack web3 developer with experience in developing cross-platform application in React Native. You could look up my portfolio: https://www.jedshock.com

### How I plan on tackling this issue
I will complete the Cashu BTC integration by finalizing hooks in packages/afk_nostr_sdk and refining mobile UI components. I'll ensure seamless wallet functionality by writing unit to end-to-end tests for sending/receiving e-cash and sats, with robust exception handling throughout. Instead of generic local storage, I'll leverage react-native-encrypted-storage, a de facto choice for secure local data management. I'll also enhance the UI experience, testing QR code generation, LN invoice payments, and P2P transfers. Additionally, I'll implement respective NIP relay selection and Lightning addresses in profiles, adhering closely to the provided documentation and wallet example.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i have experience in blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience integrating wallet functionalities and enhancing UI in mobile applications, which will facilitate a smooth Cashu BTC integration.

### How I plan on tackling this issue
I would test the Cashu BTC wallet for sending/receiving ecash and sats, enhance the UI components, ensure that all proofs and invoices are correctly saved in local storage, and implement features like QR code generation and LN invoice payments. Additionally, I would focus on upgrading the necessary screens for contact management, history, and invoice handling.

**Comment by jaiminRaiyani** [comment]
Can I handle this task?

**Comment by Kaminar-i** [comment]
Please, I'd like to have the opportunity to contribute to this project

**Comment by lindsaymoralesb** [comment]
Hello! Lindsay - Software Engineer with 4.5+ years of exp and multiple contributions to this project.

Can I hop into this one? I had previously worked on enhancing the main cashu screen and some components. Would love to keep working with the cashu integration!
ETA:
- for screens improvements: 1-2 days
- testing: 1 day
- qr code integration: 1 day

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by MrRoudyk** [comment]
May I take care of this?

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by lindsaymoralesb** [comment]
Could I be assigned to this?

**Comment by lindsaymoralesb** [comment]
Hello! Lindsay Morales - Software Engineer with +4.5 years of experience and multiple contributions to this project.
I recently worked refactoring the Cashu Wallet module for this project so I have the context of what has been implemented here.
Now I would work on nip implementations and also on integrating the receive ecash feature using url.
ETA: 2-3 days
