### ISSUE TITLE
Launchpad Cairo & Solidity

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#174]
# Description

We need to finish the Launchpad features, test, check and release it for an audit.
The LaunchpadPump is a Cairo contract to create, launch, buy and sell token.

# TODO 

If you have questions, ping me on TG

- [ ]  Do all assert needed in the buy and sell function: Buy_token check threshold_liquidity with quote_amount, supply_available, amount received etc.
- [ ] Verify the math of the bonding curve formula for BUY and SELL: _get_amount_by_type_of_coin_or_quote
- [ ] Test for amount received based on the bonding curve formula
- [ ] Testing add_liquidity function: Mock Jediswap V2
- [ ] Add Ekubo exchange: add_liquidity, present in the Unruggable repo

**Comment by JoE11-y** [comment]
Can I take a look at this @MSghais

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
I'd start by reviewing the current state of the contract, then proceed to work on the task.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
@JoE11-y I am a smart contract dev

### How I plan on tackling this issue
if this is assigned to me i would:

- Review LaunchpadPump contract and requirements

- further implement assertions functions

- Verify the bonding curve calculations

- Do all required testing

- Integrate Ekubo exchange's `add_liquidity` function from Unruggable repo.

- Test and debug

I will let you know if i need anything

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a returning contributor having worked specifically on the launchpad feature.

### How I plan on tackling this issue
I will continue on debugging and testing the features that need to be added to finish the launchpad integration.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I have previously contributed to the project multiple times. I can complete the asked tasks of asserting necessary implementations in buy, sell functions, verifying the math of the bonding curve formula, testing the add_liquidity_function and adding ekudo exchange for liquidity
ETA - 2 days
