### ISSUE TITLE
Fix Art-peace

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#187]
# Description

We need to fix our Art-peace repo, that's need to correctly for on Sepolia Testnet.

Requirements to run the Art-peace part: 
Run PWA in /apps/pwa
Test it in Mobile
Run Backend Golang in /backend

Add .env in /apps/pwa: NEXT_PUBLIC_CANVAS_STARKNET_CONTRACT_ADDRESS=0x1c3e2cae24f0f167fb389a7e4c797002c4f0465db29ecf1753ed944c6ae746e

# Todo

UI:

- [ ] Connect account fixed (you can directly place pixel without reload)
- [ ] Fix Session Wallet
- [ ] Fix Username store when logged
- [ ] Everything work smoothly and LFG

Indexer:

- [ ] When you click in a Pixel, that's need to create a TX : add the Art-peace address deploy, available in the /packages/common or here: 0x1c3e2cae24f0f167fb389a7e4c797002c4f0465db29ecf1753ed944c6ae746e
- [ ] Check if Pixel are saved in Redis/DB
- [ ] Fix indexer Art-peace

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Can I handle this task?

**Comment by Gianfranco99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have been a developer for over 4 years and have been contributing to the Starknet ecosystem for more than a year. My recent contributions include work on cairo-lint and scaffold-starknet. I’m eager to participate in this project as I see a lot of potential in it and believe it adds valuable functionality to the Starknet ecosystem.

### How I plan on tackling this issue
I would start by setting up the environment as outlined in the issue, ensuring both the PWA and backend are correctly running in Sepolia Testnet.

Add Contract and Connect Account: First, I will ensure that the correct contract is set in the PWA using the provided address, and then verify that the account connection works seamlessly by debugging the connection flow.

Handle Pixel Interaction: I will implement the logic that triggers a transaction whenever a pixel is clicked, utilizing the provided Art-peace contract address. This will involve connecting the frontend to the StarkNet wallet and creating a transaction to update the pixel data.

Pixel Persistence: After the transaction, I will verify if the pixel's data is correctly stored in the Redis/DB. If necessary, I will debug the integration with the backend services to ensure data is persistently saved.

Fix Indexer for Art-peace: Finally, I will review the indexer to ensure it's functioning correctly with the Art-peace contract and reflect any updates from the transactions made on the pixels. This will involve analyzing logs and traces to fix any issues with the current indexing mechanism.

**Comment by ctangarife** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Backend Developer | Automation Enthusiast

I'm a backend developer driven by a passion for continuous learning. I focus on acquiring new skills either based on project needs or out of personal curiosity. My approach is centered on providing practical solutions to processes that take up too much time. If something can be automated, I rarely do it more than twice. I enjoy creating bash scripts to speed up my workflow.

I have experience in Go, JavaScript, Python, Docker, MongoDB, and I use Git for version control to ensure seamless development.

"Laziness is the mother of automation."

### How I plan on tackling this issue
The first thing I do is analyze the potential impact. Then, I review the functions involved leading up to the issue. After that, I focus on the specific function, checking the logic that might be causing the problem.

**Comment by manlikeHB** [comment]
hey @MSghais, can I work on this?

**Comment by NueloSE** [comment]
@MSghais can I work on this?  ETA<=24hrs

**Comment by ooochoche** [comment]
@MSghais I have gone through the description, and I can work on this!

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i have experience in blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a rust dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by jaiminRaiyani** [comment]
Can I start working on this?

**Comment by shubha-me** [comment]
Mind if I take this issue?

**Comment by bruhhgnik** [comment]
I’d like to work on this,
ETA: 2-3 days at max

**Comment by jedstroke** [comment]
Can I jump on this task?

**Comment by mimisavage** [comment]
Can I take this from here?

**Comment by GoSTEAN** [comment]
Is it okay if I take this?

**Comment by Supa-mega** [comment]
I'd like to handle this task.

**Comment by CEOliam** [comment]
Can I take this from here?

**Comment by mymiracle0118** [comment]
Could I take a shot at this?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by DuendexCR** [comment]
Can I jump on this task?

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by Dorcas18** [comment]
Could I take a shot at this?

**Comment by olisaagbafor** [comment]
Can I be assigned to this?

**Comment by ryzen-xp** [comment]
I’d like to help with this.

**Comment by danielrobotz** [comment]
Can I start working on this?

**Comment by michojekunle** [comment]
Can I take this issue?
