### ISSUE TITLE
Soulbond and Token bound token

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#268]
# Description

Create a Soulbond with no transferable and Token bound account that can inherit and manage token.

# Tasks

- [ ] Create a Soulbond components 
- [ ] Create a Token bound token.
- [ ] Factory to create this.

**Comment by Iwueseiter** [comment]
Let me try this one!
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.
 ETA: 48hrs

**Comment by casweeney** [comment]
## About me:
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


## Tackling this issue:
- Given that I have a deep understanding of composability and components on Cairo, I will create a `soulbound` contract using the Soulbound component.
- I will also create a Token bound token.
- I will create a factory contract that creates this token.

**Comment by akintewe** [comment]
Can I tackle this one?

**Comment by Supa-mega** [comment]
Let me handle this issue!

**Comment by MSghais** [comment]
> ## About me:
> I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking
> 
> I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.
> 
> Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.
> 
> ## Tackling this issue:
> * Given that I have a deep understanding of composability and components on Cairo, I will create a `soulbound` contract using the Soulbound component.
> * I will also create a Token bound token.
> * I will create a factory contract that creates this token.

Gm, can you ping me on Telegram? We have also a Staking contract to do in Cairo

**Comment by mimisavage** [comment]
Could I take on this issue?

**Comment by aniruddhaaps** [comment]
To address this issue I would

Develop Soulbound components that follow SNIP-14: Non-transferable.
Create a Token-Bound Account contract that can inherit and manage tokens using smart contract logic.
Design a factory contract that can deploy and initialize, dynamically, Soulbound accounts and any Token-Bound tokens associated with them.

**Comment by ncoquelet** [comment]
I'm a senior fullstack dev, assign me some of your tasks and I'm committed to finishing them by the end of the next few weeks.

**Comment by NueloSE** [comment]
I can handle this issue kindly assign me.  Am a frontend developer with some level of experience building web applications.

**Comment by CEOliam** [comment]
Mind if I try this one?

**Comment by htiennv** [comment]
Hi @MSghais, I would like to take this issue. I have experienced implementation contract protocol in solidity, solana, cairo

**Comment by 7-falseparfait** [comment]
I’d like to resolve this.

**Comment by ShantelPeters** [comment]
I’d love to work on this task.

**Comment by DuendexCR** [comment]
Could I grab this task?

**Comment by Amarjeet325** [comment]
I’d like to help with this.

**Comment by Dorcas18** [comment]
Could I grab this task?

**Comment by olisaagbafor** [comment]
Mind if I take this issue?

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Cairo.

I will like to take care of this. Will follow the above requirements and create a good PR within 24hours.

**Comment by jaiminRaiyani** [comment]
Can I take care of this issue?

**Comment by Kaminar-i** [comment]
Can I take up this issue? I’ll ensure to deliver a satisfactory result within 48 hours.

**Comment by FadhilMulinya** [comment]
I’d like to resolve this.

**Comment by danielrobotz** [comment]
I'd love to give this a go.

**Comment by Nityam573** [comment]
Can I jump on this task?

**Comment by nikkybel** [comment]
Can I start working on this?
