### ISSUE TITLE
Launchpad: Fix share_users map and get_share_of_user_by_contract

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#328]
# Description

launchpad.cairo to fix and prio.

Fix share map and get_share_by_user of the new version.

Before we used : Map::(ContractAddress,ContractAddress), SharesTokenUser
Now we change to: Map::<ContractAddress, Map::<ContractAddress, SharesTokenUser>>

Verify all the changes made, get functions of share is broken now

# Tasks

- [ ] Fix share_users map with recent changes
- [ ] Fix get_share_of_user_by_contract Option: unwrap failed
- [ ] Check bonding_type params
- [ ] Add the get_share_of_user_by_contract in the launchpad_tests before a sell to get the amount_owned

**Comment by MSghais** [comment]
Lfg, let's also read the get_share in the launchpad_tests to sell the amount_owned.
