### ISSUE TITLE
Solidity contract to mint aBTC

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#35]
# Description

Solidity contract to mint aBTC with a one-to-one mint with wBTC, tBTC, cbBTC and more.

# TODO 
- [] Architecture and Doc of the implementation
- [] Mapping of BTC wrapped like tBTC, wBTC, cbBTC etc.
- [] ERC20 or ERC4626 aBTC with Access control from OpenZepellin: https://docs.openzeppelin.com/contracts/5.x/erc4626
- [] Deposit function
-[] Withdraw function
- [] Cross call into Cairo
- [] Upgradeable contract if possible

**Comment by martinvibes** [comment]
i

**Comment by Gift-Naomi** [comment]
@MSghais i can work on this

**Comment by ShantelPeters** [comment]
Hi @MSghais i can work on this .

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue


. Here's how I would approach the Solidity contract to mint aBTC with a one-to-one mint with wBTC, tBTC, cbBTC and more, as a single Pull Request (PR):

**Issue: Solidity Contract to Mint aBTC with a One-to-One Mint with wBTC, tBTC, cbBTC and More**

**Description:**
I will create a Solidity contract to mint aBTC (Aragon Bitcoin), a synthetic asset representing Bitcoin, with a one-to-one mint with other Bitcoin-backed assets like wBTC, tBTC, and cbBTC. This will involve creating a `mintVaultBTC` contract and a separate contract for a reserve of wBTC.

**Tasks:**

**Architecture:**
1. I will design the overall architecture of the solution, including the relationship between the `mintVaultBTC` contract and the wBTC reserve contract.
2. I will determine the necessary data structures and state variables to track the minting, burning, and reserves of aBTC.
3. I will consider the security implications and potential attack vectors to ensure the contract is secure and robust.

**Deposit Function:**
1. I will implement the deposit function that allows users to deposit wBTC, tBTC, cbBTC, or other supported Bitcoin-backed assets into the contract.
2. I will ensure the deposit function correctly verifies the input assets and updates the corresponding aBTC balance.
3. I will consider edge cases, such as partial deposits or unsupported assets, and handle them appropriately.

**Withdraw Function:**
1. I will implement the withdraw function that allows users to burn their aBTC and receive the equivalent amount of the underlying Bitcoin-backed asset.
2. I will ensure the withdraw function correctly verifies the user's aBTC balance, burns the tokens, and transfers the corresponding asset back to the user.
3. I will handle potential edge cases, such as insufficient aBTC balance or unsupported assets.

**Cross Call into Cairo:**
1. I will research and understand the integration between Solidity and the Cairo programming language, which is used in the Ethereum-based Starknet ecosystem.
2. I will implement the necessary cross-chain functionality to enable interaction between the Solidity contract and the Cairo-based components, such as the aBTC token contract.
3. I will ensure the cross-chain communication is secure and reliable, following best practices for cross-chain integration.

**Pull Request (PR) Workflow:**
1. I will create a new branch for the "aBTC Minting" feature.
2. I will submit a single pull request that includes all the tasks: Architecture, Deposit Function, Withdraw Function, and Cross Call into Cairo.
3. I will ensure the pull request includes comprehensive tests and documentation for the implemented features.
4. I will collaborate with the team to address any feedback or reviews during the pull request process.

By including all the tasks in a single Pull Request, I can ensure that the development process is streamlined and the entire feature is reviewed and merged together. This approach allows for better code cohesion and easier tracking of the feature's progress.


Given the complexity of the issue i propose an honest 5-6 Days ETA, as i would need to do proper research.
My Breakdown:

Day 1: Architecture and basic setup
Day 2: Core contract and token mapping
Day 3: Deposit and withdraw functions
Day 4: Access control and upgradability
Day 5: Cross-chain integration with Cairo
Day 6: Final testing, documentation, and optimization

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am Sagar Rana, a full stack and blockchain engineer with over a year of experience in writing smart contracts. I have been writing smart contracts for a year now with languages such as Solidity, Vyper, Cairo, Rust and Noir. I can write contracts involving transactions with minimal gas fees. 

### How I plan on tackling this issue
1.Define Supported Tokens:
- Create a mapping to track which wrapped BTC tokens (e.g., wBTC, tBTC, cbBTC) are supported.
- Add functions to add/remove supported tokens, only accessible by admin.

2. Create aBTC Token Using ERC4626:
- Use OpenZeppelin’s ERC4626 standard to create aBTC as a tokenized vault.
- Implement access control with roles for admin and minter using OpenZeppelin’s AccessControl.

3. Implement Deposit Function:
- Ensure the deposit function accepts only supported tokens.
- Mint equivalent aBTC to the user upon deposit.
```
function deposit(address token, uint256 amount) public {
    require(supportedTokens[token], "Unsupported token");
    IERC20(token).transferFrom(msg.sender, address(this), amount);
    _mint(msg.sender, amount);  // Mint equivalent aBTC
}

```

4. Implement Withdraw Function:
- Allow users to burn aBTC and withdraw the corresponding amount of the supported token.
- Ensure the withdraw function handles multiple tokens securely
```
function withdraw(address token, uint256 amount) public {
    require(supportedTokens[token], "Unsupported token");
    _burn(msg.sender, amount);  // Burn aBTC
    IERC20(token).transfer(msg.sender, amount);  // Return equivalent wrapped BTC
}

```

5. Handle Cross-Chain Calls (Cairo Integration):
- Emit an event or use a bridge contract for cross-chain functionality with Cairo.

6. Make the Contract Upgradeable (Optional):
- Use OpenZeppelin’s upgradeable contracts for future-proofing.

**Comment by SoarinSkySagar** [comment]
Hey @MSghais, I think I will be able to resolve this issue, please assign

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
I will implement the aBTC contract with the following approach:

Create an upgradeable ERC20 contract using OpenZeppelin:
Implement ERC20Upgradeable for token functionality
Use AccessControlUpgradeable for role-based permissions
Implement UUPSUpgradeable for future upgrades

Add support for wrapped BTC tokens:
Create a mapping to track supported tokens (wBTC, tBTC, cbBTC, etc.)
Implement admin functions to add/remove supported tokens

Develop core minting functionality:
Create deposit() function for 1:1 minting of aBTC
Implement withdraw() function for burning aBTC and receiving wrapped BTC

Research and implement Cairo cross-call functionality:
Explore bridge or oracle solutions for StarkNet integration
Implement secure cross-chain communication

Set up testing and deployment:
Write unit and integration tests
Use Hardhat for local development and testing
Deploy using an upgradeable proxy pattern

ETA- 3-4 days

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> ### My background and how it can be leveraged
> 
> I am Sagar Rana, a full stack and blockchain engineer with over a year of experience in writing smart contracts. I have been writing smart contracts for a year now with languages such as Solidity, Vyper, Cairo, Rust and Noir. I can write contracts involving transactions with minimal gas fees.
> ### How I plan on tackling this issue
> 
> 1.Define Supported Tokens:
> 
>     * Create a mapping to track which wrapped BTC tokens (e.g., wBTC, tBTC, cbBTC) are supported.
> 
>     * Add functions to add/remove supported tokens, only accessible by admin.
> 
> 
>     2. Create aBTC Token Using ERC4626:
> 
> 
>     * Use OpenZeppelin’s ERC4626 standard to create aBTC as a tokenized vault.
> 
>     * Implement access control with roles for admin and minter using OpenZeppelin’s AccessControl.
> 
> 
>     3. Implement Deposit Function:
> 
> 
>     * Ensure the deposit function accepts only supported tokens.
> 
>     * Mint equivalent aBTC to the user upon deposit.
> 
> 
> ```
> function deposit(address token, uint256 amount) public {
>     require(supportedTokens[token], "Unsupported token");
>     IERC20(token).transferFrom(msg.sender, address(this), amount);
>     _mint(msg.sender, amount);  // Mint equivalent aBTC
> }
> ```
> 
>     4. Implement Withdraw Function:
> 
> 
>     * Allow users to burn aBTC and withdraw the corresponding amount of the supported token.
> 
>     * Ensure the withdraw function handles multiple tokens securely
> 
> 
> ```
> function withdraw(address token, uint256 amount) public {
>     require(supportedTokens[token], "Unsupported token");
>     _burn(msg.sender, amount);  // Burn aBTC
>     IERC20(token).transfer(msg.sender, amount);  // Return equivalent wrapped BTC
> }
> ```
> 
>     5. Handle Cross-Chain Calls (Cairo Integration):
> 
> 
>     * Emit an event or use a bridge contract for cross-chain functionality with Cairo.
> 
> 
>     6. Make the Contract Upgradeable (Optional):
> 
> 
>     * Use OpenZeppelin’s upgradeable contracts for future-proofing.
> 
> 
>     7. Create a comprehensive and well structured documentation
> 
> 
> ## ETA: 3 days

@SoarinSkySagar can you ping me in Telegram please? MSG_Encrypted
