### ISSUE TITLE
TG Miniapp test Sepolia with Art peace

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#354]
# Description

We work on integration the Telegram Argent SDK.

We need to finish and test the integration of it in the apps/pwa for the Pixel game and more coming soon. Maybe we are gonna add it also in the apps/mobile after

# How to

- [ ] Run the data-backend with the env of your Telegram app (apps/pwa)
- [ ] Run PWA

# Tasks

- [ ] Find a way to used the Argent SDK wallet as an account the starknet react useAccount() hooks? If it's possible easily. Otherwise we need to create a hook that's used on of this account (starknet react or argent telegram)
- [ ] Test Telegram argent account in Sepolia and Telegram dev
- [ ] Do a Pixel place transaction in the Telegram app in Miniapp context connected with Telegram
- [ ] Add more features to interact with

**Comment by blessingbytes** [comment]
I’d love to work on this task.

**Comment by Judah04** [comment]
Hi @MSghais, I'd love to work on this issue.

**Comment by ncoquelet** [comment]
May I try my hand at this?

**Comment by caxtonacollins** [comment]
May I handle this issue?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by akintewe** [comment]
Can I try solving this issue?

**Comment by addegbenga** [comment]
Mind if I take this issue?
Eta 48hrs
