### ISSUE TITLE
Finish Hook of List and Bookmark

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#80]
NIP-51 description here:
https://github.com/nostr-protocol/nips/blob/master/51.md

## Description

Finish hooks and add bookmark/List in the UI.
## TODO:

- [ ] Fix the bookmark list to have all event in their tags, init if it's not already created: check example in the useEditContacts hook
- [] List of tags, interest etc, private and public
- [ ] Bookmark view for an User in their profile
- [ ] See list created by users and open

**Comment by Iwueseiter** [comment]
Hi @MSghais can I work on this?

**Comment by lindsaymoralesb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a Software Engineer based in Costa Rica. I've already successfully contributed to the last 4 ODHacks in various projects, feel free to check my profile and contributions.
I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development.

### How I plan on tackling this issue
I've already contributed to this project so I have a good knowledge of the codebase to get started right away.
I have already taken a general look at the NIP-51 shared, but I'll start by diving deep into it to better understand it, will reach over dm if any doubts.
I'll also take a look at the already created hook (useEditContacts) to fix the bookmarks one.
After that I'll start the integration of the bookmarks on the User Profile.

**Comment by MSghais** [comment]
> Hi @MSghais can I work on this?

You need to apply on Only Dust, give a description and an ETA please

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> 
> ### My background and how it can be leveraged
> I'm a Software Engineer based in Costa Rica. I've already successfully contributed to the last 4 ODHacks in various projects, feel free to check my profile and contributions. I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development.
> 
> ### How I plan on tackling this issue
> I've already contributed to this project so I have a good knowledge of the codebase to get started right away. I have already taken a general look at the NIP-51 shared, but I'll start by diving deep into it to better understand it, will reach over dm if any doubts. I'll also take a look at the already created hook (useEditContacts) to fix the bookmarks one. After that I'll start the integration of the bookmarks on the User Profile.

Awesome! Do you have an ETA please?

**Comment by lindsaymoralesb** [comment]
Yes, sorry @MSghais I estimate a couple of days to have it ready for review.

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!
I have over 5 years of experience with JavaScript, React, TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica.


### How I plan on tackling this issue
Id follow this approach: 

- review https://github.com/nostr-protocol/nips/blob/master/51.md documentation
- Ill fix the bookmarks, check existing hooks used them as guide as well to add the Bookmark view for an User in their profile
- Ill check through dm in case on any doubt! 

ETA around a couple of days, 2.5, by Saturday should be ready for review!

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
 I experience integrating complex features and APIs. I can complete the NIP-51 hooks, implement bookmark functionality, and enhance the user interface.

### How I plan on tackling this issue
I would approach this issue with the following steps?
Review NIP-51:
 Understand the specification and requirements for hooks and bookmarks.
Update Hooks:
 Complete and refine hooks to handle bookmark and tag functionality, ensuring they initialize correctly.
Implement Bookmark UI: Develop and integrate the bookmark list with tags, interests, and user profiles.
Test: 
Ensure the bookmark list displays events correctly and that users can view and manage their bookmarks.
Deploy:
 Roll out changes and monitor for issues, making adjustments as necessary.

**Comment by MSghais** [comment]
close by #90  and #105
